styria_photo/photo/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('photo.views',
    url(r'^$', 'index', name='index'),
    url(r'^(?P<user>\w+)/$', 'user_photo_list', name='user_photo_list'),
    url(r'^(?P<user>\w+)/(?P<pk>\d+)/$', 'photo_detail', name='photo_detail'),
)

styria_photo/styria_photo/urls.py
from django.conf.urls import patterns, include, url

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^', include('photo.urls', namespace='home', app_name='home')),
)
urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

styria_photo/home/models.py
from django.db import models

# Create your models here.

styria_photo/photo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill, SmartResize
from django.core.urlresolvers import reverse_lazy
from django.dispatch import receiver


def upload_to_path(instance, filename):
    return 'images/{}/{}'.format(instance.author.username if instance.author else 'user_anon', filename)


class Photo(models.Model):
    name = models.CharField(_(u'name'), max_length=50)
    author = models.ForeignKey(User, verbose_name=_(u'author'), null=True, blank=True)
    pub_date = models.DateTimeField(_(u'publication date'), auto_now_add=True)
    image = models.ImageField(_(u'image'), upload_to=upload_to_path, max_length=255)
    image_thumb = ImageSpecField((ResizeToFill(75, 75), ), image_field='image', format='JPEG', options={'quality': 90})
    image_big = ImageSpecField((SmartResize(640, 640), ), image_field='image', format='JPEG', options={'quality': 90})
    description = models.TextField(_(u'description'), max_length=150, blank=True)
    avg_rating = models.FloatField(null=True)

    @property
    def average_rating(self):
        return round(self.avg_rating, 2) if self.avg_rating is not None else _(u'Unrated')

    class Meta:
        verbose_name = _('Photo')
        verbose_name_plural = _('Photos')
        ordering = ('-pub_date', )

    def delete(self, *args, **kwargs):
        self.image.storage.delete(self.image.path)
        super(Photo, self).delete(*args, **kwargs)

    def get_absolute_url(self):
        return reverse_lazy('home:photo_detail', kwargs={'user': self.author.username if self.author else 'anon', 'pk': self.id})

    def __unicode__(self):
        return self.name


class Rating(models.Model):
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
    image = models.ForeignKey('Photo', verbose_name=_(u'image'))
    rater = models.ForeignKey(User, verbose_name=_(u'rater'))
    rating = models.PositiveSmallIntegerField(_(u'image rating'), choices=RATING_CHOICES)
    pub_date = models.DateTimeField(_(u'publication date'), auto_now_add=True)

    class Meta:
        verbose_name = _('Rating')
        verbose_name_plural = _('Ratings')

    def __unicode__(self):
        return 'Rating for {}'.format(self.image)


@receiver([models.signals.post_save, models.signals.post_delete], sender=Rating)
def update_average(sender, instance, **kwargs):
    instance.image.avg_rating = sender.objects.filter(image=instance.image).aggregate(models.Avg('rating'))['rating__avg']
    instance.image.save()

styria_photo/photo/forms.py
from __future__ import absolute_import
from .models import Photo, Rating
import floppyforms as forms
from django.utils.translation import ugettext_lazy as _


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ('name', 'image', 'description',)
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': _(u'image name...')}),
            'image': forms.ClearableFileInput(attrs={'placeholder': _(u'upload your image...')}),
            'description': forms.Textarea(attrs={'placeholder': _(u'describe this image in short...'), 'rows': 2, 'cols': 50}),
        }

    def save(self, force_insert=False, force_update=False, commit=True):
        m = super(PhotoForm, self).save(commit=False)
        m.author = self.instance.user if not self.instance.user.is_anonymous() else None
        if commit:
            m.save()
        return m


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ('rating',)
        widgets = {
            'rating': forms.Select(attrs={'id': 'starrating'}),
        }

    def save(self, force_insert=False, force_update=False, commit=True):
        m = super(RatingForm, self).save(commit=False)
        m.rater = self.instance.user
        m.image = self.instance.image
        if commit:
            m.save()
        return m

styria_photo/home/views.py
# Create your views here.

styria_photo/photo/views.py
from __future__ import absolute_import
from django.views.generic import ListView, CreateView
from .forms import PhotoForm, RatingForm
from .models import Photo, Rating
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from djpjax import PJAXResponseMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse_lazy


class UserPhotoListView(PJAXResponseMixin, ListView):
    template_name = 'photo_list.html'
    paginate_by = 12

    def get_queryset(self):
        if self.kwargs['user'] == 'anon':
            user = None
        else:
            user = get_object_or_404(User, username__iexact=self.kwargs['user'])
        if self.request.GET.get('ordering'):
            return Photo.objects.filter(author=user).order_by(self.request.GET.get('ordering'))
        return Photo.objects.filter(author=user)

    def get_context_data(self, **kwargs):
        print type(self.request.user)
        context = super(UserPhotoListView, self).get_context_data(**kwargs)
        if self.object_list[0].author:
            context['is_author'] = self.request.user == self.object_list[0].author

        return context

user_photo_list = UserPhotoListView.as_view()


class PhotoListView(PJAXResponseMixin, CreateView):
    model = Photo
    form_class = PhotoForm
    template_name = 'photo_list.html'

    def get_context_data(self, **kwargs):
        if self.request.GET.get('ordering'):
            photo_list = Photo.objects.order_by(self.request.GET.get('ordering'))
        else:
            photo_list = Photo.objects.all()
        paginator = Paginator(photo_list, 12)
        page = self.request.GET.get('page')
        try:
            photos = paginator.page(page)
        except PageNotAnInteger:
            photos = paginator.page(1)
        except EmptyPage:
            photos = paginator.page(paginator.num_pages)
        kwargs['page_obj'] = photos
        return super(PhotoListView, self).get_context_data(**kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(PhotoListView, self).form_valid(form)

index = PhotoListView.as_view()


class PhotoDetailView(PJAXResponseMixin, CreateView):
    model = Rating
    form_class = RatingForm
    template_name = 'photo_detail.html'

    def get_success_url(self):
        return reverse_lazy('home:photo_detail', kwargs={'user': self.kwargs['user'], 'pk': self.kwargs['pk']})

    def get_context_data(self, **kwargs):
        context = super(PhotoDetailView, self).get_context_data(**kwargs)
        if self.kwargs['user'] != 'anon':
            get_object_or_404(User, username__iexact=self.kwargs['user'])

        context['photo'] = get_object_or_404(Photo, pk=self.kwargs['pk'])
        context['ratings'] = Rating.objects.filter(image=self.kwargs['pk']).order_by('-pub_date')[:5]
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.image = Photo.objects.get(pk=self.kwargs['pk'])
        return super(PhotoDetailView, self).form_valid(form)

photo_detail = PhotoDetailView.as_view()

styria_photo/home/templates/base.html
{% load i18n %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}{% blocktrans %}Stryia photos - job contest{% endblocktrans %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">


        <link rel="stylesheet" href="{{ STATIC_URL }}css/normalize.min.css">
        <link rel="stylesheet" href="{{ STATIC_URL }}css/main.css">
        <link rel="stylesheet" href="{{ STATIC_URL }}css/fancybox/jquery.fancybox.css?v=2.1.4" type="text/css" media="screen" />
        <link rel="stylesheet" href="{{ STATIC_URL }}css/fancybox/jquery.fancybox-buttons.css?v=1.0.5" type="text/css" media="screen" />
        <link rel="stylesheet" href="{{ STATIC_URL }}css/fancybox/jquery.fancybox-thumbs.css?v=1.0.7" type="text/css" media="screen" />
        <link rel="stylesheet" href="{{ STATIC_URL }}css/rateit.css" type="text/css" media="screen" />

        <script src="{{ STATIC_URL }}js/vendor/modernizr-2.6.2.min.js"></script>

    </head>
    <body>
        {% include "header.html" %}

        {% block subheader%}{% endblock %}
         <hr/>
        <div id="content">
            {% block content %}<p>Hello world! This is HTML5 Boilerplate.</p>{% endblock %}
        </div>

        {% include "footer.html" %}
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="{{ STATIC_URL }}js/vendor/jquery-1.9.1.min.js"><\/script>')</script>
        <script src="{{ STATIC_URL }}js/vendor/jquery.pjax.js"></script>

        <script type="text/javascript" src="{{ STATIC_URL }}js/vendor/jquery.mousewheel-3.0.6.pack.js"></script>
        <script type="text/javascript" src="{{ STATIC_URL }}js/vendor/fancybox/jquery.fancybox.pack.js?v=2.1.4"></script>
        <script type="text/javascript" src="{{ STATIC_URL }}js/vendor/fancybox/jquery.fancybox-buttons.js?v=1.0.5"></script>
        <script type="text/javascript" src="{{ STATIC_URL }}js/vendor/fancybox/jquery.fancybox-media.js?v=1.0.5"></script>
        <script type="text/javascript" src="{{ STATIC_URL }}js/vendor/fancybox/jquery.fancybox-thumbs.js?v=1.0.7"></script>
        <script type="text/javascript" src="{{ STATIC_URL }}js/vendor/jquery.rateit.min.js"></script>
        <script type="text/javascript" src="{{ STATIC_URL }}js/vendor/jquery.rateit.js"></script>
        <script type="text/javascript" src="{{ STATIC_URL }}js/vendor/jquery.easydate-0.2.4.js"></script>
        <script src="{{ STATIC_URL }}js/plugins.js"></script>
        <script src="{{ STATIC_URL }}js/main.js"></script>
        <script type="text/javascript">
            $(document).ready(function() {
                $(".fancybox").fancybox({
                    beforeLoad: function() {
                        this.title = $(this.element).attr('caption');
                    }
                });
            });
        </script>
    </body>
</html>

styria_photo/home/templates/comments/form.html
{% load comments i18n %}
<form action="{% comment_form_target %}" method="post" id="comment-form">
    {% csrf_token %}
    <p>
        <label for="id_name">{% trans "name: " %}</label>
        {{ form.name }}
    </p>
    <p>
        <label for="id_email">{% trans "email: " %}</label>
        {{ form.email }}
    </p>
    <p>
        <label for="id_comment">{% trans "comment: " %}</label>
        {{ form.comment }}
    </p>
    {{ form.honeypot }}
    {{ form.content_type }}
    {{ form.object_pk }}
    {{ form.timestamp }}
    {{ form.security_hash }}
    <input type="submit" value="{% trans "post comment" %}">
</form>
{% comment %}        
<form action="{% comment_form_target %}" method="post">{% csrf_token %}
  {% if next %}<div><input type="hidden" name="next" value="{{ next }}" /></div>{% endif %}
  {% for field in form %}
    {% if field.is_hidden %}
      <div>{{ field }}</div>
    {% else %}
      {% if field.errors %}{{ field.errors }}{% endif %}
      <p
        {% if field.errors %} class="error"{% endif %}
        {% ifequal field.name "honeypot" %} style="display:none;"{% endifequal %}>
        {{ field.label_tag }} {{ field }}
      </p>
    {% endif %}
  {% endfor %}
  <p class="submit">
    <input type="submit" name="post" class="submit-post" value="{% trans "Post" %}" />
    <input type="submit" name="preview" class="submit-preview" value="{% trans "Preview" %}" />
  </p>
</form>
{% endcomment %}

styria_photo/home/templates/comments/preview.html
{% extends "comments/base.html" %}
{% load i18n %}

{% block title %}{% trans "Preview your comment" %}{% endblock %}

{% block content %}
  {% load comments %}
  <form action="{% comment_form_target %}" method="post" id="comment-form">{% csrf_token %}
    {% if next %}<div><input type="hidden" name="next" value="{{ next }}" /></div>{% endif %}
    {% if form.errors %}
    <h1>{% blocktrans count counter=form.errors|length %}Please correct the error below{% plural %}Please correct the errors below{% endblocktrans %}</h1>
    {% else %}
    <h1>{% trans "Preview your comment" %}</h1>
      <blockquote>{{ comment|linebreaks }}</blockquote>
      <p>
      {% trans "and" %} <input type="submit" name="submit" class="submit-post" value="{% trans "Post your comment" %}" id="submit" /> {% trans "or make changes" %}:
      </p>
    {% endif %}
      <p>
        {% if form.name.errors %}
        <br />
        {{ form.name.errors }}
        {% endif %}
          <label for="id_name">{% trans "name: " %}</label>
          {{ form.name }}

      </p>
      <p>
        {% if form.email.errors %}
        <br />
        {{ form.email.errors }}
        {% endif %}
          <label for="id_email">{% trans "email: " %}</label>
          {{ form.email }}

      </p>
      <p>
        {% if form.comment.errors %}
        <br />
          {{ form.comment.errors }}
        {% endif %}
          <label for="id_comment">{% trans "comment: " %}</label>
          {{ form.comment }}
      </p>
      {{ form.honeypot }}
      {{ form.content_type }}
      {{ form.object_pk }}
      {{ form.timestamp }}
      {{ form.security_hash }}
    <p class="submit">
    <input type="submit" name="submit" class="submit-post" value="{% trans "Post" %}" />
    </p>
  </form>
{% endblock %}

styria_photo/home/templates/footer.html
<hr />
<footer>
    <span>This project has been made by Borislav Petrović, for purposes of getting a job @ Styria</span>
</footer>

styria_photo/home/templates/header.html
{% url "home:index" as index %}
<header id="header">
    {% if request.path == index %}
        <img src="{{ STATIC_URL }}img/styria_logo.jpg" />
    {% else %}
        <a href="{% url "home:index" %}">
            <img src="{{ STATIC_URL }}img/styria_logo.jpg" />
        </a>
    {% endif %}
    <h1>PHOTO HUT</h1>
</header>

styria_photo/photo/templates/photo_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load comments %}

{% block content %}
    <div id="photo-detail">
        <a class="fancybox" href="{{ photo.image.url }}" caption="{{ photo.name }}"><img src="{{ photo.image_big.url }}" alt="{{ photo.name }}"></a>
    </div>
    <div id="photo-sidebar">
        <div id ="average-rating">
            <p class="avg">{{ photo.average_rating }}</p>
            <p>{% trans "average rating" %}</p>
        </div>
        {% if not request.user.is_anonymous %}
        <div id="rating-container">
            <form action="." method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="rateit" data-rateit-backingfld="#starrating" data-rateit-step="1" id="ratingstars"></div>
                <p>
                    <input type="submit" value="{% trans "rate it" %}" />
                </p>
            </form>
        </div>
        {% endif %}
        <div id="latest-rating">
            <span>{% trans "latest ratings" %}</span>
            {% for rating in ratings %}
                <p class="rating-{% filter force_escape %}{% cycle 'odd' 'even' %}{% endfilter %}">
                    {% blocktrans with rating=rating.rating rater=rating.rater %}{{ rater }} gave this photo a rating of: {{ rating }} {% endblocktrans %}</p>
            {% endfor %}
        </div>
        <div id="photo-info" >
            <p id="photo.author">{% trans "Author: " %}{{ photo.author }}</p>
            <p id="photo-desc">{% trans "Description: " %}{{ photo.description }}</p>
            <p>
                {% get_comment_count for photo as comment_count %}
                {% trans "This photo has " %}<span id="comment-count">{% if comment_count == 0 %}{% trans "no comments" %} {% else %} {{ comment_count }} {% trans " comments" %} {% endif %}</span>
            </p>
        </div>
    </div>
    <div id="comment-list">
        <span>{% trans "comment on this photo" %}</span>
        {% get_comment_list for photo as comment_list%}
        {% for comment in comment_list %}
        <div id="comment-{{ comment.id }}" class="comment-{% filter force_escape %}{% cycle 'odd' 'even' %}{% endfilter %}">
            <span>{{ comment.comment }}</span><span id="comment-author-info"> - by <a href="mailto:{{ comment.email }}">{{ comment.name }}</a></span> - <span class="easydate">{{ comment.submit_date|date:"r" }}</span>
        </div>
        {% empty %}
            <span>
                {% blocktrans %}
                There are currently no comments related to this photo <br/> Try commenting on it yourself
                {% endblocktrans %}
            </span>
        {% endfor %}
    </div>
    <div id="jaxmsg">
    </div>
    <div class="comment-form" id="container">
        {% get_comment_form for photo as form %}
        <form action="{% comment_form_target %}" method="post" id="comment-form">
            {% csrf_token %}
            <p>
                <label for="id_name">{% trans "name: " %}</label>
                {{ form.name }}
            </p>
            <p>
                <label for="id_email">{% trans "email: " %}</label>
                {{ form.email }}
            </p>
            <p>
                <label for="id_name">{% trans "comment: " %}</label>
                {{ form.comment }}
            </p>
            {{ form.honeypot }}
            {{ form.content_type }}
            {{ form.object_pk }}
            {{ form.timestamp }}
            {{ form.security_hash }}
            <input type="submit" value="{% trans "post comment" %}">
        </form>
    </div>
{% endblock %}

styria_photo/photo/templates/photo_list-pjax.html
{% load i18n %}
{% for photo in page_obj %}
<div class="{% if forloop.counter0|divisibleby:"4" %}rowend{% endif %} photobox-{% filter force_escape %}{% cycle 'odd' 'even' %}{% endfilter %}">
    <a href="{{ photo.get_absolute_url }}"><img src="{{ photo.image_thumb.url }}" alt="{{ photo.name }}"></a>
    {% url "home:index" as index %}
    {% if photo.author == request.user and request.path != index %}
    {% else %}
        <p> by
            <a href="{% if photo.author %}{% url "home:user_photo_list" photo.author.username %}{% else %}{% url "home:user_photo_list"  user='anon' %}{% endif %}">{% if photo.author %} {{ photo.author.username }}{% else %} {% trans "anonymous" %} {% endif %}</a>
        </p>
    {% endif %}
    <p>{{ photo.description }}</p>
</div>
{% empty %}
    <p>
        {% blocktrans %}
        We apologize, but there aren't any photos available for display.Try uploading a photo yourself!!!"
        {% endblocktrans %}
    </p>
{% endfor %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}&ordering={{ request.GET.ordering }}" class="pjax">{% trans "previous" %}</a>
        {% endif %}

        <span class="current">
            {% trans "Page" %} {{ page_obj.number }} {% trans "of" %} {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}&ordering={{ request.GET.ordering }}" class="pjax">{% trans "next" %}</a>
        {% endif %}
    </span>
</div>

styria_photo/photo/templates/photo_list.html
{% extends "base.html" %}
{% load i18n %}
{% load floppyforms %}
{% block title %}
    {{ block.super }}
    {% url "home:index" as index %} -
    {% if request.path == index %}{% trans "Home" %}{% else %} {% trans "Photos" %}{% endif %}
{% endblock %}
{% block subheader %}
{% url "home:index" as index %}
    {% if request.path == index %}
    <hr />
    <div id="file-upload">
        <form method="post" action="." enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <p>
                <input type="submit" value="{% trans "upload image" %}" />
            </p>
        </form>
    </div>
    {% else %}
        <h2>{% trans "Welcome to " %}{% if is_author %}{% trans "your" %} {% else %}{% if page_obj.0.author == None %} {% trans "anonymous " %}{% else %} {{ page_obj.0.author }}{% endif %}{% endif %} {% trans " gallery" %}</h2>
    {% endif %}
{% endblock %}

{% block content %}
    <div id="subtitle"><h2>{% trans "Photo gallery" %}</h2></div>
    <div id="ordering">
        <form action="." method="get">
            <select name="ordering" id="ordering">
                <option value="">------------</option>
                <option value="avg_rating">{% trans "lowest rated" %}</option>
                <option value="-avg_rating">{% trans "highest rated" %}</option>
                <option value="pub_date">{% trans "oldest" %}</option>
                <option value="-pub_date">{% trans "latest" %}</option>
            </select>
            <input type="submit" value="{% trans "order" %}" />
        </form>
    </div>
    <div class="photo-container" id="container">

        {% include "photo_list-pjax.html" %}
        {% comment %}
        {% for photo in page_obj %}
        <div class="{% if forloop.counter0|divisibleby:"4" %}rowend{% endif %} photobox-{% filter force_escape %}{% cycle 'odd' 'even' %}{% endfilter %}">
            <a href="{{ photo.get_absolute_url }}"><img src="{{ photo.image_thumb.url }}" alt="{{ photo.name }}"></a>
            {% url "home:index" as index %}
            {% if photo.author == request.user and request.path != index %}
            {% else %}
                <p> by
                    <a href="{% if photo.author %}{% url "home:user_photo_list" photo.author.username %}{% else %}{% url "home:user_photo_list"  user='anon' %}{% endif %}">{% if photo.author %} {{ photo.author.username }}{% else %} {% trans "anonymous" %} {% endif %}</a>
                </p>
            {% endif %}
            <p>{{ photo.description }}</p>
        </div>
        {% empty %}
            <p>
                {% blocktrans %}
                We apologize, but there aren't any photos available for display.Try uploading a photo yourself!!!"
                {% endblocktrans %}
            </p>
        {% endfor %}
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}&ordering={{ request.GET.ordering }}">{% trans "previous" %}</a>
                {% endif %}

                <span class="current">
                    {% trans "Page" %} {{ page_obj.number }} {% trans "of" %} {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}&ordering={{ request.GET.ordering }}">{% trans "next" %}</a>
                {% endif %}
            </span>
        </div>
        {% endcomment %}
    </div>
{% endblock %}

styria_photo/photo/templates/rating_form.html
<form method="post" action=".">
    {% csrf_token %}
    {{ form.as_p }}
    <p>
        <input type="submit" value="rate it" />
    </p>
</form>